# Generated by Django 4.1.7 on 2023-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.URLField(),
        ),
    ]
